export type ErrorKey =
  | 'VALIDATION_FAILED'
  | 'BAD_REQUEST'
  | 'UNAUTHORIZED'
  | 'INVALID_CREDENTIALS'
  | 'INVALID_TOKEN'
  | 'MISSING_BEARER'
  | 'MISSING_API_KEY'
  | 'INVALID_API_KEY'
  | 'API_KEY_REVOKED'
  | 'INVALID_REFRESH_TOKEN'
  | 'TWOFA_REQUIRED'
  | 'INVALID_2FA_CODE'
  | 'TWOFA_ALREADY_ENABLED'
  | 'TWOFA_NOT_ENABLED'
  | 'TWOFA_NOT_STARTED'
  | 'TWOFA_USE_TOTP'
  | 'TWOFA_USE_EMAIL'
  | 'TWOFA_CODE_USED'
  | 'TWOFA_PROVIDE_CODE'
  | 'FORBIDDEN'
  | 'ACCOUNT_SUSPENDED'
  | 'ACCOUNT_DELETED'
  | 'ACCOUNT_LOCKED'
  | 'EMAIL_NOT_VERIFIED'
  | 'API_KEY_IP_DENIED'
  | 'USER_NOT_OWNED'
  | 'INVALID_INVITE'
  | 'INVITE_EMAIL_MISMATCH'
  | 'INVALID_VERIFICATION'
  | 'CAPTCHA_FAILED'
  | 'WRONG_PASSWORD'
  | 'RESTORE_INVALID'
  | 'ACCOUNT_NOT_DELETED'
  | 'NO_PASSWORD_SET'
  | 'SAME_EMAIL'
  | 'TRADEURL_LIMIT'
  | 'TRADEURL_ALREADY_ADDED'
  | 'TRADEURL_INVALID_TOKEN'
  | 'TRADEURL_ESCROW'
  | 'RESET_INVALID'
  | 'TRADEURL_NOT_FOUND'
  | 'DISCORD_ALREADY_LINKED'
  | 'DISCORD_NOT_LINKED'
  | 'DISCORD_OAUTH_FAILED'
  | 'NOT_FOUND'
  | 'USER_NOT_FOUND'
  | 'CONFLICT'
  | 'EMAIL_TAKEN'
  | 'STEAM_ID_TAKEN'
  | 'EXTERNAL_ID_TAKEN'
  | 'INSUFFICIENT_BALANCE'
  | 'WALLET_SUSPENDED'
  | 'WALLET_NOT_FOUND'
  | 'INVALID_CURRENCY'
  | 'IDEMPOTENCY_CONFLICT'
  | 'IDEMPOTENCY_KEY_REQUIRED'
  | 'INVALID_AMOUNT'
  | 'TRANSFER_CURRENCY_MISMATCH'
  | 'MERCHANT_MUST_BE_USD'
  | 'FX_RATE_UNAVAILABLE'
  | 'DEPOSIT_NOT_FOUND'
  | 'DEPOSIT_NOT_CANCELLABLE'
  | 'DEPOSIT_NOT_RESUMABLE'
  | 'INVALID_QUOTE'
  | 'INVALID_CHAIN'
  | 'INVALID_DEPOSIT_CURRENCY'
  | 'DEPOSIT_MIN_AMOUNT'
  | 'INVALID_SIGNATURE'
  | 'GATEWAY_ERROR'
  | 'RATE_LIMITED'
  | 'INVALID_ADMIN_OP'
  | 'APIKEY_LIMIT_REACHED'
  | 'APIKEY_ALREADY_REVOKED'
  | 'SECRET_ALREADY_EXISTS'
  | 'SECRET_NOT_FOUND'
  | 'SECRET_ALREADY_REVOKED'
  | 'WEBHOOK_TEST_FAILED'
  | 'WEBHOOK_NOT_FOUND'
  | 'WEBHOOK_DELIVERY_NOT_FOUND'
  | 'WEBHOOK_URL_INVALID'
  | 'INVALID_FEE_BPS'
  | 'SUB_USER_HAS_BALANCE'
  | 'CRYPTO_NOT_CONFIGURED'
  | 'CRYPTO_CHAIN_NOT_SUPPORTED'
  | 'CRYPTO_CHAIN_PAUSED'
  | 'CRYPTO_TOKEN_NOT_SUPPORTED'
  | 'CRYPTO_ADDRESS_NOT_FOUND'
  | 'CRYPTO_MIN_AMOUNT'
  | 'CRYPTO_INVALID_DESTINATION'
  | 'CRYPTO_WITHDRAWAL_NOT_FOUND'
  | 'CRYPTO_WITHDRAWAL_INVALID_STATE'
  | 'CRYPTO_WEBHOOK_INVALID'
  | 'CRYPTO_SELF_TRANSFER'
  | 'CRYPTO_RECIPIENT_WALLET_MISSING'
  | 'MARKET_UNAVAILABLE'
  | 'MARKET_TIMEOUT'
  | 'ORDER_NOT_FOUND'
  | 'PRICE_MISMATCH'
  | 'TRADEURL_REQUIRED'
  | 'PURCHASE_FAILED'
  | 'CALLBACK_INVALID'
  | 'LISTING_NOT_FOUND'
  | 'LISTING_DETAIL_FAILED'
  | 'WORKER_LOW_BALANCE'
  | 'PURCHASE_RETRY_TIMEOUT'
  | 'PRICE_BELOW_MINIMUM'
  | 'TRADE_NOT_CANCELLABLE'
  | 'TRADE_CANCEL_TOO_SOON'
  | 'INTERNAL'
  | 'MAINTENANCE_MODE'
  | 'SDK_TIMEOUT'
  | 'SDK_NETWORK'
  | 'SDK_ABORTED'
  | 'SDK_INVALID_RESPONSE'
  // Open-ended fallback so unknown server keys still typecheck.
  | (string & {});

// HTTP status mapping for server-side keys; SDK-side keys use 0.
export const ERROR_STATUS: Record<string, number> = {
  VALIDATION_FAILED: 422, BAD_REQUEST: 400,
  UNAUTHORIZED: 401, INVALID_CREDENTIALS: 401, INVALID_TOKEN: 401, MISSING_BEARER: 401,
  MISSING_API_KEY: 401, INVALID_API_KEY: 401, API_KEY_REVOKED: 401, INVALID_REFRESH_TOKEN: 401,
  FORBIDDEN: 403, ACCOUNT_SUSPENDED: 403, ACCOUNT_DELETED: 403, ACCOUNT_LOCKED: 403,
  EMAIL_NOT_VERIFIED: 403, API_KEY_IP_DENIED: 403, USER_NOT_OWNED: 403,
  NOT_FOUND: 404, USER_NOT_FOUND: 404,
  CONFLICT: 409, EMAIL_TAKEN: 409, IDEMPOTENCY_CONFLICT: 409, PRICE_MISMATCH: 409,
  RATE_LIMITED: 429,
  INSUFFICIENT_BALANCE: 422,
};

// Category sets used by isAuthError / isRateLimited / isValidationError.
export const AUTH_ERROR_KEYS = new Set<string>([
  'UNAUTHORIZED', 'INVALID_CREDENTIALS', 'INVALID_TOKEN', 'MISSING_BEARER',
  'MISSING_API_KEY', 'INVALID_API_KEY', 'API_KEY_REVOKED', 'INVALID_REFRESH_TOKEN',
  'FORBIDDEN', 'ACCOUNT_SUSPENDED', 'ACCOUNT_DELETED', 'ACCOUNT_LOCKED',
  'EMAIL_NOT_VERIFIED', 'API_KEY_IP_DENIED', 'USER_NOT_OWNED',
]);

export const VALIDATION_ERROR_KEYS = new Set<string>([
  'VALIDATION_FAILED', 'BAD_REQUEST',
]);

export const RATE_LIMIT_ERROR_KEYS = new Set<string>([
  'RATE_LIMITED',
]);
